"""Pydantic schemas 聚合导出(2026-08-06 重构)。

Admin 部分合并到 admin.py,删除了原 admin_auth.py / admin.py / admin_users.py 三个文件。
"""
from app.schemas.admin import (
    AdminAuditItem,
    AdminAuditResponse,
    AdminAuditSummaryItem,
    AdminAuditSummaryResponse,
    AdminChangePasswordRequest,
    AdminChangePasswordResponse,
    AdminCodeListItem,
    AdminCodeListResponse,
    AdminCodeLookupResponse,
    AdminCodeRevokeResponse,
    AdminGrantBalanceRequest,
    AdminGrantBalanceResponse,
    AdminIssueCodesRequest,
    AdminIssueCodesResponse,
    AdminIssuedCodeItem,
    AdminLoginRequest,
    AdminMeResponse,
    AdminMetricsSummary,
    AdminRevokeSessionsRequest,
    AdminRevokeSessionsResponse,
    AdminUpdateUserRequest,
    AdminUpdateUserResponse,
    AdminUserDetail,
    AdminUserListItem,
    AdminUserListResponse,
)
from app.schemas.auth import (
    BalanceOut,
    LogoutRequest,
    RedeemRequest,
    RedeemResponse,
    RefreshRequest,
    TokensOut,
    UserOut,
)
from app.schemas.billing import (
    CostPreview,
    EstimateRequest,
    PreauthRequest,
    PreauthResponse,
    PricingRule,
    PricingTier,
    RefundRequest,
    RefundResponse,
    SettleRequest,
    SettleResponse,
)
from app.schemas.errors import ApiErrorBody, ApiErrorEnvelope
from app.schemas.user import BillListResponse, BillOut, UserAccountOut

__all__ = [
    # admin
    "AdminLoginRequest",
    "AdminMeResponse",
    "AdminChangePasswordRequest",
    "AdminChangePasswordResponse",
    "AdminUserListItem",
    "AdminUserListResponse",
    "AdminUserDetail",
    "AdminUpdateUserRequest",
    "AdminUpdateUserResponse",
    "AdminGrantBalanceRequest",
    "AdminGrantBalanceResponse",
    "AdminRevokeSessionsRequest",
    "AdminRevokeSessionsResponse",
    "AdminIssueCodesRequest",
    "AdminIssuedCodeItem",
    "AdminIssueCodesResponse",
    "AdminCodeListItem",
    "AdminCodeListResponse",
    "AdminCodeLookupResponse",
    "AdminCodeRevokeResponse",
    "AdminAuditItem",
    "AdminAuditResponse",
    "AdminAuditSummaryItem",
    "AdminAuditSummaryResponse",
    "AdminMetricsSummary",
    # auth
    "BalanceOut",
    "LogoutRequest",
    "RedeemRequest",
    "RedeemResponse",
    "RefreshRequest",
    "TokensOut",
    "UserOut",
    # billing
    "CostPreview",
    "EstimateRequest",
    "PreauthRequest",
    "PreauthResponse",
    "PricingRule",
    "PricingTier",
    "RefundRequest",
    "RefundResponse",
    "SettleRequest",
    "SettleResponse",
    # errors
    "ApiErrorBody",
    "ApiErrorEnvelope",
    # user
    "BillListResponse",
    "BillOut",
    "UserAccountOut",
]